spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cshr
    username: postgres
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: validate # validate schema on run.  Changes are performed by liquibase in the db-rpg-populated-postgres repository.
server:
  port: 8080
